FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm ci
COPY . .

ARG VITE_URL_INICIAL_GESTOR
ARG VITE_URL_INICIAL_DINAMICA
ARG VITE_URL_INICIAL_ESTADISTICAS
ARG VITE_URL_INICIAL_DEMO
ARG VITE_URL_INICIAL_ESTATICA
ARG VITE_URL_INICIAL_METAMAPA
ARG VITE_URL_INICIAL_GETAWAY
ARG VITE_URL_GOOGLE_AUTH
ARG VITE_URL_GRAPHQL

ENV VITE_URL_INICIAL_GESTOR=$VITE_URL_INICIAL_GESTOR \
    VITE_URL_INICIAL_DINAMICA=$VITE_URL_INICIAL_DINAMICA \
    VITE_URL_INICIAL_ESTADISTICAS=$VITE_URL_INICIAL_ESTADISTICAS \
    VITE_URL_INICIAL_DEMO=$VITE_URL_INICIAL_DEMO \
    VITE_URL_INICIAL_ESTATICA=$VITE_URL_INICIAL_ESTATICA \
    VITE_URL_INICIAL_METAMAPA=$VITE_URL_INICIAL_METAMAPA \
    VITE_URL_INICIAL_GETAWAY=$VITE_URL_INICIAL_GETAWAY \
    VITE_URL_GOOGLE_AUTH=$VITE_URL_GOOGLE_AUTH \
    VITE_URL_GRAPHQL=$VITE_URL_GRAPHQL

RUN npm run build

FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
